name: KICS Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  kics:
    runs-on: ubuntu-latest
    name: Run KICS Scan
    steps:
      - uses: actions/checkout@v2
      - name: Run KICS scan
        uses: Checkmarx/kics-github-action@v1.6
        with:
          path: '.'
