name: Vorpal Code Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vorpal-scan:
    runs-on: ubuntu-latest
    name: Vorpal Static Code Analysis
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Vorpal Scan
        uses: Checkmarx/vorpal-action@v1
        with:
          path: '.'
